insert into books (isbn, title, author)
values ('isbn1', 'Emma', 'Jane Austen')
     , ('isbn2', 'The Idiot', 'Fyodor Dostoyevsky')
     , ('isbn3', 'Game of Thrones', 'George R.R. Martin')
     , ('isbn4', 'Romeo and Juliet', 'William Shakespeare')
     , ('isbn5', 'Mockingjay', 'Suzanne Collins')
     , ('isbn6', 'One Hundred Years of Solitude', 'Gabriel García Márquez')
     , ('isbn7', 'In Cold Blood', 'Truman Capote')
     , ('isbn8', 'Jane Eyre', 'Charlotte Bronte')
     , ('isbn9', 'The Secret History', 'Donna Tartt')
     , ('isbn10', 'The Call of the Wild', 'Jack London')
     , ('isbn11', 'The Chrysalids', 'John Wyndham')
     , ('isbn12', 'Moby-Dick', 'Herman Melville')
     , ('isbn13', 'The Lion, the Witch and the Wardrobe', 'C.S. Lewis')
     , ('isbn14', 'The Death of the Heart', 'Elizabeth Bowen')
     , ('isbn15', 'Frankenstein', 'Mary Shelley')
     , ('isbn16', 'The Master and Margarita', 'Mikhail Bulgakov')
     , ('isbn17', 'The Go-Between', 'L. P. Hartley')
     , ('isbn18', 'Buddenbrooks', 'Thomas Mann')
     , ('isbn19', 'The Grapes of Wrath', 'John Steinbeck')
     , ('isbn20', 'Beloved', 'Toni Morrison');
